### ISSUE TITLE
virtio disk paging dies

### ISSUE THREAD

**Issue by dzavalishin** [dzavalishin/phantomuserland#181]
Need active virtue disk tests?

**Comment by my2coins** [comment]
Not sure if this is the issue, but ci-snaptest.sh dies during the pass 2 while doing pgout when running on virtio. The thing is pretty reproduceable in QEMU 2.0. Surprisingly, no panic occurs, but I was able to trace down to the final point which happened in the stats window:

`(gdb) 

snprintf_func (ch=50, arg=0x414dfe4c) at subr_prf.c:548
548	    struct snprintf_arg *const info = arg;
(gdb) 

550	    if (info->remain >= 2) {
(gdb) 
551	        *info->str++ = ch;
(gdb) 


552	        info->remain--;
(gdb) 

554	}
(gdb) 
kvprintf (fmt=0x1eed88 "ms\033[37mtats \033[32mw\033[37mindows        \033[32m?\033[37m - help\n \033[32mStep %d, uptime %dd, %02d:%02d:%02d\033[37m, %d events\n Time %04d/%02d/%02d %02d:%02d:%02d GMT, CPU 0 %2d%% idle\n", func=0x1e2abf <snprintf_func>, arg=0x414dfe4c, radix=10, ap=0x414dfea4 "\367\003") at subr_prf.c:635
635	        while ((ch = (u_char)*fmt++) != '%' || stop) {
(gdb) 

Remote connection closed
(gdb) 
`

**Comment by my2coins** [comment]
Is this panic connected to the issue?
```
#4  0x001a76eb in panic (fmt=0x1f250c "virtio.c:%u, %s: assertion 'desc[nout].addr' failed") at t_panic.c:49
        ap = 0x4023fdfc "\b\002"
#5  0x001500b0 in virtio_detach_buffers_list (vd=0x4910d60 <vdev>, qindex=0, nDesc=10, desc=0x4023fe74, dataLen=0x4023fe70) at virtio.c:520
        r = 0x6f0600
        nout = 0
        __func__ = "virtio_detach_buffers_list"
        pos = 15
        bufIndex = 71
        __FUNCTION__ = "virtio_detach_buffers_list"
        flagsCopy = 2
        nextCopy = 65535
#6  0x0014d522 in vio_intr_dpc_func (a=0x0) at driver_virtio_disk.c:377
        vd = 0x4910d60 <vdev>
        cmd = {{addr = 0, len = 16, flags = 1, next = 0}, {addr = 127314944, len = 512, flags = 1, next = 93}, {addr = 76616280, len = 1, flags = 2, next = 65535}, {addr = 7415316872411708, len = 1076100848, flags = 65220, next = 16419}, {addr = 9223372036875787264, len = 31, flags = 65248, next = 16419}, {addr = 1732691, len = 2, flags = 16, next = 0}, {addr = 133143986694, len = 2, flags = 65280, next = 16419}, {addr = 4621818018078638061, len = 1746843, flags = 65296, next = 16419}, {addr = 7318452475424851, len = 7303168, flags = 65328, next = 16419}, {addr = 335787758747630056, len = 6, flags = 65328, next = 16419}}
        dlen = 513
        nRead = 3
        __FUNCTION__ = "vio_intr_dpc_func"
        __func__ = "vio_intr_dpc_func"
#7  0x0013ba38 in dpc_request_run () at dpc.c:83
        i = 0x4910d94 <vio_intr_dpc>
#8  0x0013ba76 in dpc_thread () at dpc.c:112
No locals.
#9  0x001a5842 in kernel_thread_starter (func=0x13ba3c <dpc_thread>) at t_create.c:127
        thread = 0x13ba3c <dpc_thread>
#10 0x001a5e76 in phantom_thread_c_starter () at t_create.c:420
        func = 0x1a5831 <kernel_thread_starter>
        arg = 0x13ba3c <dpc_thread>
        t = 0x6f7000
#11 0x001a89b8 in phantom_thread_trampoline () at /home/gvs/compile/phantom/phantom/threads/ia32/thread.S:99
No locals.
```
It only happens when running both virtio and IDE disks, I never caught it running with virtio only.

**Comment by dzavalishin** [comment]
looks like it is.

**Comment by my2coins** [comment]
Fresh run with pure virtio ended up in the same panic on pass 2 (after recovering from the snapshot). The serial0.log is attached. Because of the bug with console wait for keypress, there's no backtrace.
[serial0.log.txt](https://github.com/dzavalishin/phantomuserland/files/188831/serial0.log.txt)

**Comment by dzavalishin** [comment]
Identical to what we have: assertion 'desc[nout].addr' failed

**Comment by dzavalishin** [comment]
Need test it, suppose it is fixed

**Comment by my2coins** [comment]
Unfortuntely, it isn't.

> Thread 1 hit Breakpoint 1, panic (fmt=0x1e2a6c "virtio.c:%u, %s: assertion 'desc[nout].addr' failed") at t_panic.c:31
> 31	    if(panic_reenter)

Sometimes it happens on 1st pass, sometimes on 2nd. Attached is the latter. Unfortunately, couldn't catch it with the full stack trace yet.
[serial0.log.txt](https://github.com/dzavalishin/phantomuserland/files/1167672/serial0.log.txt)
