### ISSUE TITLE
Phantom hangs in ne2000 driver

### ISSUE THREAD

**Issue by my2coins** [dzavalishin/phantomuserland#338]
bt full:

```
0x001508b7 in __inb (port=50183) at /home/gvs/compile/phantom/include/ia32/pio.h:92
92  __IN(b,"")
(gdb) bt full
#0  0x001508b7 in __inb (port=50183) at /home/gvs/compile/phantom/include/ia32/pio.h:92
        _v = 92 '\\'
        port = 50183
#1  0x0015133a in ne_interrupt (_dev=0x6f6300) at driver_isa_ne2000.c:309
        dev = 0x6f6300
        pvt = 0x6f0180
        status = 76615008
#2  0x001128b9 in call_irq_handler (s=0x4173ff1c, irq=11) at intrdisp.c:114
        it = 0x6aee40
#3  0x001814eb in hal_PIC_interrupt_dispatcher (ts=0x4173ff1c, mask=21010594) at interrupts.c:51
        irq = 11
#4  0x00178fd7 in call_handler () at intr.S:144
No locals.
#5  0x4173ff1c in ?? ()
No symbol table info available.
#6  0x001a5842 in kernel_thread_starter (func=0x106709 <usb_check_event>) at t_create.c:127
        thread = 0x106709 <usb_check_event>
#7  0x001a5e76 in phantom_thread_c_starter () at t_create.c:420
        func = 0x1a5831 <kernel_thread_starter>
        arg = 0x106709 <usb_check_event>
        t = 0x1409800
#8  0x001a89b8 in phantom_thread_trampoline () at /home/gvs/compile/phantom/phantom/threads/ia32/thread.S:99

```

**Comment by dzavalishin** [comment]
Can you, please, verify that port number 50183 is really Ne2000 device port in this QEMU config?

**Comment by my2coins** [comment]
In my understanding, 50183 is the dynamically assigned tcp port (an outgoing TCP connection, most probably), it has nothing to do with QEMU config. What did I miss?

**Comment by dzavalishin** [comment]
it's io port, not tcp port :)

**Comment by dzavalishin** [comment]
CPU in instruction, hardware io

**Comment by dzavalishin** [comment]
io port addr this code references is 0xC407, and QEMU info pci says ne2k addr segment is 0xc100...0xc1FF. Could you please plress Ctrl-Alt-2 and type info pci on your QEMU version? There must be info on PCI Ethernet controller address range. Does it include 0xC407?

**Comment by my2coins** [comment]
It says:
```
Bus 0, device 3, function 0:
  Ethernet controller: PCI device 10ec:8029
  IRQ 11.
  BAR0: I/O at 0xc400 [0xc4ff]
 
```
So that, it appears to be correct.

**Comment by dzavalishin** [comment]
Pity.
