### ISSUE TITLE
init sema panic

### ISSUE THREAD

**Issue by my2coins** [dzavalishin/phantomuserland#353]
[serial0.log.txt](https://github.com/dzavalishin/phantomuserland/files/236072/serial0.log.txt)
```
31	    if(panic_reenter)
(gdb) #0  panic (fmt=0x200fe6 "init sema!") at t_panic.c:31
        ap = 0x1350400 ""
#1  0x001a52a8 in checkinit (c=0x6a402c <uhci_intr_sem>) at sem.c:76
No locals.
#2  0x001a593a in hal_sem_release (c=0x6a402c <uhci_intr_sem>) at sem.c:420
No locals.
#3  0x0010b123 in uhci_int (arg=0x0) at usb-uhci.c:258
No locals.
#4  0x001131b8 in call_irq_handler (s=0x414dfe20, irq=11) at intrdisp.c:114
        it = 0x70d580
#5  0x0018215b in hal_PIC_interrupt_dispatcher (ts=0x414dfe20, mask=226) at interrupts.c:51
        irq = 11
#6  0x00179c47 in call_handler () at intr.S:144
No locals.
#7  0x414dfe20 in ?? ()
No symbol table info available.
#8  0x0013ec5e in phantom_debug_window_loop () at console_win.c:479
        bp = 0x5
        len = 115
        sec = 2662879723520
        hr = 199813
        rc = 2
        min = 76359099
        days = 0
        mt = {tm_sec = 4, tm_min = 116, tm_hour = 3, tm_mday = 0, tm_mon = 0, tm_year = 0, tm_wday = 0, tm_yday = 0, tm_isdst = 0, tm_gmtoff = 0, tm_zone = 0x0}
        buf = " Switch view: \033[32mt\033[37mhreads \033[32ms\033[37mtats \033[32mw\033[37mindows        \033[32m?\033[37m - help\n \033[32mStep 4, uptime 0d, 00:00:02\033[37m, 0 events\n Time 2016/04/26 07:04:24 GMT, CPU 0 97% idle\n\033[35m Statist"...
        step = 20251648
        show = 0
        wx = 0
        tty = 0x0
#9  0x001a5b02 in kernel_thread_starter (func=0x13eae5 <phantom_debug_window_loop>) at t_create.c:127
        thread = 0x13eae5 <phantom_debug_window_loop>
#10 0x001a6136 in phantom_thread_c_starter () at t_create.c:425
        func = 0x1a5af1 <kernel_thread_starter>
        arg = 0x13eae5 <phantom_debug_window_loop>
        t = 0x1350400
#11 0x001a8ee8 in phantom_thread_trampoline () at /home/gvs/compile/phantom/phantom/threads/ia32/thread.S:99

```

**Comment by my2coins** [comment]
Caught it again while attempting to run the snaptest. Looks like things got harder. Logs are attached.

[gdb.log.txt](https://github.com/dzavalishin/phantomuserland/files/333861/gdb.log.txt)
[serial0.log.txt](https://github.com/dzavalishin/phantomuserland/files/333862/serial0.log.txt)

**Comment by dzavalishin** [comment]
turned off USB stack for a while
